// Generated by the Crawlora platform client generator. Do not edit.
export const operations = {
  "fotmob-audio-matches": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-audio-matches",
    "method": "GET",
    "path": "/fotmob/audio-matches",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-fifa-ranking-periods": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-fifa-ranking-periods",
    "method": "GET",
    "path": "/fotmob/fifa-ranking-periods",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "men",
          "women"
        ],
        "in": "query",
        "name": "gender",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-fifa-rankings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-fifa-rankings",
    "method": "GET",
    "path": "/fotmob/fifa-rankings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "men",
          "women"
        ],
        "in": "query",
        "name": "gender",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "period_id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-latest-news": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-latest-news",
    "method": "GET",
    "path": "/fotmob/latest-news",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "start_index",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-league": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-league",
    "method": "GET",
    "path": "/fotmob/league",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "league_id",
        "required": true,
        "type": "integer"
      },
      {
        "in": "query",
        "name": "season",
        "type": "string"
      },
      {
        "in": "query",
        "name": "shotmap",
        "type": "boolean"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-leagues": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-leagues",
    "method": "GET",
    "path": "/fotmob/leagues",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-lineup-builder-players": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-lineup-builder-players",
    "method": "GET",
    "path": "/fotmob/lineup-builder-players",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "player_ids",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-lineup-builder-team": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-lineup-builder-team",
    "method": "GET",
    "path": "/fotmob/lineup-builder-team",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "team_id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-match": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-match",
    "method": "GET",
    "path": "/fotmob/match",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-match-media": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-match-media",
    "method": "GET",
    "path": "/fotmob/match-media",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-matches": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-matches",
    "method": "GET",
    "path": "/fotmob/matches",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "date",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "timezone",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-news": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-news",
    "method": "GET",
    "path": "/fotmob/news",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "league_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "start_index",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-news-article": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-news-article",
    "method": "GET",
    "path": "/fotmob/news-article",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-player": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-player",
    "method": "GET",
    "path": "/fotmob/player",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "include_market_values",
        "type": "boolean"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-player-match-stats": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-player-match-stats",
    "method": "GET",
    "path": "/fotmob/player-match-stats",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "player_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "match_id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-player-matches": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-player-matches",
    "method": "GET",
    "path": "/fotmob/player-matches",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "player_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "league_id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "team_id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "before",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-player-stats": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-player-stats",
    "method": "GET",
    "path": "/fotmob/player-stats",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "player_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season_id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-search",
    "method": "GET",
    "path": "/fotmob/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "term",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-seasons": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-seasons",
    "method": "GET",
    "path": "/fotmob/seasons",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "league_id",
        "required": true,
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-stats": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-stats",
    "method": "GET",
    "path": "/fotmob/stats",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "league_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season_id",
        "type": "string"
      },
      {
        "enum": [
          "players",
          "teams"
        ],
        "in": "query",
        "name": "type",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "stat",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "team_id",
        "type": "string"
      },
      {
        "enum": [
          "all",
          "striker",
          "winger",
          "attackingMidfielder",
          "midfielder",
          "fullback",
          "centerBack"
        ],
        "in": "query",
        "name": "position",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-stats-categories": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-stats-categories",
    "method": "GET",
    "path": "/fotmob/stats-categories",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "league_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season_id",
        "type": "string"
      },
      {
        "enum": [
          "players",
          "teams"
        ],
        "in": "query",
        "name": "type",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-table": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-table",
    "method": "GET",
    "path": "/fotmob/table",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "league_id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-team": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-team",
    "method": "GET",
    "path": "/fotmob/team",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-team-fixtures": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "cursorParams": [
      "cursor"
    ],
    "formParams": [],
    "id": "fotmob-team-fixtures",
    "method": "GET",
    "paginatable": true,
    "path": "/fotmob/team-fixtures",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "team_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "cursor",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-team-news": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-team-news",
    "method": "GET",
    "path": "/fotmob/team-news",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "team_id",
        "required": true,
        "type": "integer"
      },
      {
        "in": "query",
        "name": "start_index",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-transfers": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-transfers",
    "method": "GET",
    "paginatable": true,
    "path": "/fotmob/transfers",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "all",
          "rumours",
          "popular"
        ],
        "in": "query",
        "name": "mode",
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      },
      {
        "enum": [
          "6months",
          "1year",
          "2years",
          "3years"
        ],
        "in": "query",
        "name": "last",
        "type": "string"
      },
      {
        "enum": [
          "all",
          "in",
          "out"
        ],
        "in": "query",
        "name": "direction",
        "type": "string"
      },
      {
        "in": "query",
        "name": "min_fee",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "max_fee",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "league_ids",
        "type": "string"
      },
      {
        "in": "query",
        "name": "team_ids",
        "type": "string"
      },
      {
        "enum": [
          "lastModified",
          "fee",
          "date",
          "name",
          "fromClubName",
          "toClubName"
        ],
        "in": "query",
        "name": "order_by",
        "type": "string"
      },
      {
        "in": "query",
        "name": "exclude_extensions",
        "type": "boolean"
      },
      {
        "in": "query",
        "name": "likely_only",
        "type": "boolean"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-trending-news": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-trending-news",
    "method": "GET",
    "path": "/fotmob/trending-news",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-trending-searches": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-trending-searches",
    "method": "GET",
    "path": "/fotmob/trending-searches",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-tv-guide": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-tv-guide",
    "method": "GET",
    "path": "/fotmob/tv-guide",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "us",
          "se",
          "gb",
          "de",
          "no",
          "es",
          "mx",
          "ar",
          "bo",
          "cl",
          "co",
          "cr",
          "ec",
          "gt",
          "hn",
          "ni",
          "pa",
          "py",
          "pe",
          "uy",
          "ve",
          "da",
          "ca",
          "au",
          "at",
          "be",
          "bg",
          "hr",
          "cy",
          "cz",
          "ee",
          "fi",
          "fr",
          "gr",
          "hu",
          "is",
          "ie",
          "il",
          "it",
          "nl",
          "pl",
          "pt",
          "ro",
          "ru",
          "ch",
          "tr",
          "za",
          "br",
          "in",
          "me",
          "id",
          "th",
          "mm",
          "al",
          "az",
          "bl",
          "ba",
          "ks",
          "la",
          "li",
          "mk",
          "rs",
          "sk",
          "ua",
          "essv",
          "nz",
          "bd",
          "cn",
          "gh",
          "hk",
          "jp",
          "kr",
          "ma",
          "mt",
          "my",
          "ng",
          "ph",
          "pk",
          "sg",
          "si",
          "tz"
        ],
        "in": "query",
        "name": "country",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "timezone",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-tv-guide-channels": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-tv-guide-channels",
    "method": "GET",
    "path": "/fotmob/tv-guide-channels",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "us",
          "se",
          "gb",
          "de",
          "no",
          "es",
          "mx",
          "ar",
          "bo",
          "cl",
          "co",
          "cr",
          "ec",
          "gt",
          "hn",
          "ni",
          "pa",
          "py",
          "pe",
          "uy",
          "ve",
          "da",
          "ca",
          "au",
          "at",
          "be",
          "bg",
          "hr",
          "cy",
          "cz",
          "ee",
          "fi",
          "fr",
          "gr",
          "hu",
          "is",
          "ie",
          "il",
          "it",
          "nl",
          "pl",
          "pt",
          "ro",
          "ru",
          "ch",
          "tr",
          "za",
          "br",
          "in",
          "me",
          "id",
          "th",
          "mm",
          "al",
          "az",
          "bl",
          "ba",
          "ks",
          "la",
          "li",
          "mk",
          "rs",
          "sk",
          "ua",
          "essv",
          "nz",
          "bd",
          "cn",
          "gh",
          "hk",
          "jp",
          "kr",
          "ma",
          "mt",
          "my",
          "ng",
          "ph",
          "pk",
          "sg",
          "si",
          "tz"
        ],
        "in": "query",
        "name": "country",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "fotmob-tv-guide-countries": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "fotmob-tv-guide-countries",
    "method": "GET",
    "path": "/fotmob/tv-guide-countries",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  }
};

export const groups = {
  "fotmob": {
    "audioMatches": "fotmob-audio-matches",
    "fifaRankingPeriods": "fotmob-fifa-ranking-periods",
    "fifaRankings": "fotmob-fifa-rankings",
    "latestNews": "fotmob-latest-news",
    "league": "fotmob-league",
    "leagues": "fotmob-leagues",
    "lineupBuilderPlayers": "fotmob-lineup-builder-players",
    "lineupBuilderTeam": "fotmob-lineup-builder-team",
    "match": "fotmob-match",
    "matchMedia": "fotmob-match-media",
    "matches": "fotmob-matches",
    "news": "fotmob-news",
    "newsArticle": "fotmob-news-article",
    "player": "fotmob-player",
    "playerMatchStats": "fotmob-player-match-stats",
    "playerMatches": "fotmob-player-matches",
    "playerStats": "fotmob-player-stats",
    "search": "fotmob-search",
    "seasons": "fotmob-seasons",
    "stats": "fotmob-stats",
    "statsCategories": "fotmob-stats-categories",
    "table": "fotmob-table",
    "team": "fotmob-team",
    "teamFixtures": "fotmob-team-fixtures",
    "teamNews": "fotmob-team-news",
    "transfers": "fotmob-transfers",
    "trendingNews": "fotmob-trending-news",
    "trendingSearches": "fotmob-trending-searches",
    "tvGuide": "fotmob-tv-guide",
    "tvGuideChannels": "fotmob-tv-guide-channels",
    "tvGuideCountries": "fotmob-tv-guide-countries"
  }
};

export const operationCount = 31;

export const OperationIds = Object.freeze({
  "FotmobAudioMatches": "fotmob-audio-matches",
  "FotmobFifaRankingPeriods": "fotmob-fifa-ranking-periods",
  "FotmobFifaRankings": "fotmob-fifa-rankings",
  "FotmobLatestNews": "fotmob-latest-news",
  "FotmobLeague": "fotmob-league",
  "FotmobLeagues": "fotmob-leagues",
  "FotmobLineupBuilderPlayers": "fotmob-lineup-builder-players",
  "FotmobLineupBuilderTeam": "fotmob-lineup-builder-team",
  "FotmobMatch": "fotmob-match",
  "FotmobMatchMedia": "fotmob-match-media",
  "FotmobMatches": "fotmob-matches",
  "FotmobNews": "fotmob-news",
  "FotmobNewsArticle": "fotmob-news-article",
  "FotmobPlayer": "fotmob-player",
  "FotmobPlayerMatchStats": "fotmob-player-match-stats",
  "FotmobPlayerMatches": "fotmob-player-matches",
  "FotmobPlayerStats": "fotmob-player-stats",
  "FotmobSearch": "fotmob-search",
  "FotmobSeasons": "fotmob-seasons",
  "FotmobStats": "fotmob-stats",
  "FotmobStatsCategories": "fotmob-stats-categories",
  "FotmobTable": "fotmob-table",
  "FotmobTeam": "fotmob-team",
  "FotmobTeamFixtures": "fotmob-team-fixtures",
  "FotmobTeamNews": "fotmob-team-news",
  "FotmobTransfers": "fotmob-transfers",
  "FotmobTrendingNews": "fotmob-trending-news",
  "FotmobTrendingSearches": "fotmob-trending-searches",
  "FotmobTvGuide": "fotmob-tv-guide",
  "FotmobTvGuideChannels": "fotmob-tv-guide-channels",
  "FotmobTvGuideCountries": "fotmob-tv-guide-countries"
});
