// Generated by scripts/generate.py. Do not edit manually.

export type CrawloraResponse<T = unknown> = T;
export type CrawloraBody<T = Record<string, unknown>> = T;

export interface ModelAppResponse {
  "code"?: number;
  "data"?: unknown;
  "msg"?: unknown;
}

export interface ModelFotmobResponseDoc {
  "code"?: number;
  "data"?: ModelFotmobSourceDataDoc;
  "msg"?: string;
}

export interface ModelFotmobSourceDataDoc {
  "data"?: Record<string, unknown>;
  "source_url"?: string;
}

export interface ModelFotmobNewsListResponseDoc {
  "code"?: number;
  "data"?: ModelFotmobSourceNewsListDoc;
  "msg"?: string;
}

export interface ModelFotmobSourceNewsListDoc {
  "data"?: Array<ModelFotmobNewsItemDoc>;
  "source_url"?: string;
}

export interface ModelFotmobNewsItemDoc {
  "gmtTime"?: string;
  "id"?: string;
  "imageUrl"?: string;
  "language"?: string;
  "lead"?: string;
  "page"?: ModelFotmobNewsItemPageDoc;
  "sourceIconUrl"?: string;
  "sourceStr"?: string;
  "title"?: string;
}

export interface ModelFotmobNewsItemPageDoc {
  "url"?: string;
}

export interface ModelFotmobFifaRankingsResponseDoc {
  "code"?: number;
  "data"?: ModelFotmobFifaRankingRowsDataDoc;
  "msg"?: string;
}

export interface ModelFotmobFifaRankingRowsDataDoc {
  "data"?: Array<ModelFotmobFifaRankingRowDoc>;
  "source_url"?: string;
}

export interface ModelFotmobFifaRankingRowDoc {
  "gainedRank"?: boolean;
  "id"?: number;
  "lostRank"?: boolean;
  "name"?: string;
  "pointsDiff"?: number;
  "previousPoints"?: number;
  "rank"?: number;
  "totalPoints"?: number;
}

export interface ModelFotmobFifaRankingPeriodsResponseDoc {
  "code"?: number;
  "data"?: ModelFotmobFifaRankingPeriodData;
  "msg"?: string;
}

export interface ModelFotmobFifaRankingPeriodData {
  "data"?: Array<ModelFotmobFifaRankingPeriodItemDoc>;
  "source_url"?: string;
}

export interface ModelFotmobFifaRankingPeriodItemDoc {
  "periodId"?: string;
  "periodName"?: string;
}

export type FotmobAudioMatchesResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobAudioMatchesParams {
}

export type FotmobFifaRankingPeriodsResponse = CrawloraResponse<ModelFotmobFifaRankingPeriodsResponseDoc>;
export interface FotmobFifaRankingPeriodsParams {
  "gender": "men" | "women";
}

export type FotmobFifaRankingsResponse = CrawloraResponse<ModelFotmobFifaRankingsResponseDoc>;
export interface FotmobFifaRankingsParams {
  "gender": "men" | "women";
  "period_id": string;
}

export type FotmobLatestNewsResponse = CrawloraResponse<ModelFotmobNewsListResponseDoc>;
export interface FotmobLatestNewsParams {
  "start_index"?: number;
}

export type FotmobLeagueResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobLeagueParams {
  "league_id": number;
  "season"?: string;
  "shotmap"?: boolean;
}

export type FotmobLeaguesResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobLeaguesParams {
}

export type FotmobLineupBuilderPlayersResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobLineupBuilderPlayersParams {
  "player_ids": string;
}

export type FotmobLineupBuilderTeamResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobLineupBuilderTeamParams {
  "team_id": string;
}

export type FotmobMatchResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobMatchParams {
  "id": string;
}

export type FotmobMatchMediaResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobMatchMediaParams {
  "id": string;
}

export type FotmobMatchesResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobMatchesParams {
  "date": string;
  "timezone"?: string;
}

export type FotmobNewsResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobNewsParams {
  "league_id": string;
  "start_index"?: number;
}

export type FotmobNewsArticleResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobNewsArticleParams {
  "id": string;
}

export type FotmobPlayerResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobPlayerParams {
  "id": string;
  "include_market_values"?: boolean;
}

export type FotmobPlayerMatchStatsResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobPlayerMatchStatsParams {
  "player_id": string;
  "match_id": string;
}

export type FotmobPlayerMatchesResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobPlayerMatchesParams {
  "player_id": string;
  "league_id"?: string;
  "team_id"?: string;
  "before"?: string;
}

export type FotmobPlayerStatsResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobPlayerStatsParams {
  "player_id": string;
  "season_id": string;
}

export type FotmobSearchResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobSearchParams {
  "term": string;
}

export type FotmobSeasonsResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobSeasonsParams {
  "league_id": number;
}

export type FotmobStatsResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobStatsParams {
  "league_id": string;
  "season_id"?: string;
  "type": "players" | "teams";
  "stat": string;
  "team_id"?: string;
  "position"?: "all" | "striker" | "winger" | "attackingMidfielder" | "midfielder" | "fullback" | "centerBack";
}

export type FotmobStatsCategoriesResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobStatsCategoriesParams {
  "league_id": string;
  "season_id"?: string;
  "type": "players" | "teams";
}

export type FotmobTableResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobTableParams {
  "league_id": string;
}

export type FotmobTeamResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobTeamParams {
  "id": string;
}

export type FotmobTeamFixturesResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobTeamFixturesParams {
  "team_id": string;
  "cursor": string;
}

export type FotmobTeamNewsResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobTeamNewsParams {
  "team_id": number;
  "start_index"?: number;
}

export type FotmobTransfersResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobTransfersParams {
  "mode"?: "all" | "rumours" | "popular";
  "page"?: number;
  "last"?: "6months" | "1year" | "2years" | "3years";
  "direction"?: "all" | "in" | "out";
  "min_fee"?: number;
  "max_fee"?: number;
  "league_ids"?: string;
  "team_ids"?: string;
  "order_by"?: "lastModified" | "fee" | "date" | "name" | "fromClubName" | "toClubName";
  "exclude_extensions"?: boolean;
  "likely_only"?: boolean;
}

export type FotmobTrendingNewsResponse = CrawloraResponse<ModelFotmobNewsListResponseDoc>;
export interface FotmobTrendingNewsParams {
}

export type FotmobTrendingSearchesResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobTrendingSearchesParams {
}

export type FotmobTvGuideResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobTvGuideParams {
  "country": "us" | "se" | "gb" | "de" | "no" | "es" | "mx" | "ar" | "bo" | "cl" | "co" | "cr" | "ec" | "gt" | "hn" | "ni" | "pa" | "py" | "pe" | "uy" | "ve" | "da" | "ca" | "au" | "at" | "be" | "bg" | "hr" | "cy" | "cz" | "ee" | "fi" | "fr" | "gr" | "hu" | "is" | "ie" | "il" | "it" | "nl" | "pl" | "pt" | "ro" | "ru" | "ch" | "tr" | "za" | "br" | "in" | "me" | "id" | "th" | "mm" | "al" | "az" | "bl" | "ba" | "ks" | "la" | "li" | "mk" | "rs" | "sk" | "ua" | "essv" | "nz" | "bd" | "cn" | "gh" | "hk" | "jp" | "kr" | "ma" | "mt" | "my" | "ng" | "ph" | "pk" | "sg" | "si" | "tz";
  "timezone"?: string;
}

export type FotmobTvGuideChannelsResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobTvGuideChannelsParams {
  "country": "us" | "se" | "gb" | "de" | "no" | "es" | "mx" | "ar" | "bo" | "cl" | "co" | "cr" | "ec" | "gt" | "hn" | "ni" | "pa" | "py" | "pe" | "uy" | "ve" | "da" | "ca" | "au" | "at" | "be" | "bg" | "hr" | "cy" | "cz" | "ee" | "fi" | "fr" | "gr" | "hu" | "is" | "ie" | "il" | "it" | "nl" | "pl" | "pt" | "ro" | "ru" | "ch" | "tr" | "za" | "br" | "in" | "me" | "id" | "th" | "mm" | "al" | "az" | "bl" | "ba" | "ks" | "la" | "li" | "mk" | "rs" | "sk" | "ua" | "essv" | "nz" | "bd" | "cn" | "gh" | "hk" | "jp" | "kr" | "ma" | "mt" | "my" | "ng" | "ph" | "pk" | "sg" | "si" | "tz";
}

export type FotmobTvGuideCountriesResponse = CrawloraResponse<ModelFotmobResponseDoc>;
export interface FotmobTvGuideCountriesParams {
}

export interface FotmobService {
  audioMatches<T = FotmobAudioMatchesResponse>(params?: FotmobAudioMatchesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  fifaRankingPeriods<T = FotmobFifaRankingPeriodsResponse>(params: FotmobFifaRankingPeriodsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  fifaRankings<T = FotmobFifaRankingsResponse>(params: FotmobFifaRankingsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  latestNews<T = FotmobLatestNewsResponse>(params?: FotmobLatestNewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  league<T = FotmobLeagueResponse>(params: FotmobLeagueParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  leagues<T = FotmobLeaguesResponse>(params?: FotmobLeaguesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  lineupBuilderPlayers<T = FotmobLineupBuilderPlayersResponse>(params: FotmobLineupBuilderPlayersParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  lineupBuilderTeam<T = FotmobLineupBuilderTeamResponse>(params: FotmobLineupBuilderTeamParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  match<T = FotmobMatchResponse>(params: FotmobMatchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchMedia<T = FotmobMatchMediaResponse>(params: FotmobMatchMediaParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matches<T = FotmobMatchesResponse>(params: FotmobMatchesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  news<T = FotmobNewsResponse>(params: FotmobNewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  newsArticle<T = FotmobNewsArticleResponse>(params: FotmobNewsArticleParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  player<T = FotmobPlayerResponse>(params: FotmobPlayerParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  playerMatchStats<T = FotmobPlayerMatchStatsResponse>(params: FotmobPlayerMatchStatsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  playerMatches<T = FotmobPlayerMatchesResponse>(params: FotmobPlayerMatchesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  playerStats<T = FotmobPlayerStatsResponse>(params: FotmobPlayerStatsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  search<T = FotmobSearchResponse>(params: FotmobSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  seasons<T = FotmobSeasonsResponse>(params: FotmobSeasonsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  stats<T = FotmobStatsResponse>(params: FotmobStatsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  statsCategories<T = FotmobStatsCategoriesResponse>(params: FotmobStatsCategoriesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  table<T = FotmobTableResponse>(params: FotmobTableParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  team<T = FotmobTeamResponse>(params: FotmobTeamParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  teamFixtures<T = FotmobTeamFixturesResponse>(params: FotmobTeamFixturesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  teamNews<T = FotmobTeamNewsResponse>(params: FotmobTeamNewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  transfers<T = FotmobTransfersResponse>(params?: FotmobTransfersParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  trendingNews<T = FotmobTrendingNewsResponse>(params?: FotmobTrendingNewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  trendingSearches<T = FotmobTrendingSearchesResponse>(params?: FotmobTrendingSearchesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tvGuide<T = FotmobTvGuideResponse>(params: FotmobTvGuideParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tvGuideChannels<T = FotmobTvGuideChannelsResponse>(params: FotmobTvGuideChannelsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tvGuideCountries<T = FotmobTvGuideCountriesResponse>(params?: FotmobTvGuideCountriesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
}

export interface CrawloraGeneratedGroups {
  fotmob: FotmobService;
}

export interface OperationParamsMap {
  "fotmob-audio-matches": FotmobAudioMatchesParams;
  "fotmob-fifa-ranking-periods": FotmobFifaRankingPeriodsParams;
  "fotmob-fifa-rankings": FotmobFifaRankingsParams;
  "fotmob-latest-news": FotmobLatestNewsParams;
  "fotmob-league": FotmobLeagueParams;
  "fotmob-leagues": FotmobLeaguesParams;
  "fotmob-lineup-builder-players": FotmobLineupBuilderPlayersParams;
  "fotmob-lineup-builder-team": FotmobLineupBuilderTeamParams;
  "fotmob-match": FotmobMatchParams;
  "fotmob-match-media": FotmobMatchMediaParams;
  "fotmob-matches": FotmobMatchesParams;
  "fotmob-news": FotmobNewsParams;
  "fotmob-news-article": FotmobNewsArticleParams;
  "fotmob-player": FotmobPlayerParams;
  "fotmob-player-match-stats": FotmobPlayerMatchStatsParams;
  "fotmob-player-matches": FotmobPlayerMatchesParams;
  "fotmob-player-stats": FotmobPlayerStatsParams;
  "fotmob-search": FotmobSearchParams;
  "fotmob-seasons": FotmobSeasonsParams;
  "fotmob-stats": FotmobStatsParams;
  "fotmob-stats-categories": FotmobStatsCategoriesParams;
  "fotmob-table": FotmobTableParams;
  "fotmob-team": FotmobTeamParams;
  "fotmob-team-fixtures": FotmobTeamFixturesParams;
  "fotmob-team-news": FotmobTeamNewsParams;
  "fotmob-transfers": FotmobTransfersParams;
  "fotmob-trending-news": FotmobTrendingNewsParams;
  "fotmob-trending-searches": FotmobTrendingSearchesParams;
  "fotmob-tv-guide": FotmobTvGuideParams;
  "fotmob-tv-guide-channels": FotmobTvGuideChannelsParams;
  "fotmob-tv-guide-countries": FotmobTvGuideCountriesParams;
}

export interface OperationResponseMap {
  "fotmob-audio-matches": FotmobAudioMatchesResponse;
  "fotmob-fifa-ranking-periods": FotmobFifaRankingPeriodsResponse;
  "fotmob-fifa-rankings": FotmobFifaRankingsResponse;
  "fotmob-latest-news": FotmobLatestNewsResponse;
  "fotmob-league": FotmobLeagueResponse;
  "fotmob-leagues": FotmobLeaguesResponse;
  "fotmob-lineup-builder-players": FotmobLineupBuilderPlayersResponse;
  "fotmob-lineup-builder-team": FotmobLineupBuilderTeamResponse;
  "fotmob-match": FotmobMatchResponse;
  "fotmob-match-media": FotmobMatchMediaResponse;
  "fotmob-matches": FotmobMatchesResponse;
  "fotmob-news": FotmobNewsResponse;
  "fotmob-news-article": FotmobNewsArticleResponse;
  "fotmob-player": FotmobPlayerResponse;
  "fotmob-player-match-stats": FotmobPlayerMatchStatsResponse;
  "fotmob-player-matches": FotmobPlayerMatchesResponse;
  "fotmob-player-stats": FotmobPlayerStatsResponse;
  "fotmob-search": FotmobSearchResponse;
  "fotmob-seasons": FotmobSeasonsResponse;
  "fotmob-stats": FotmobStatsResponse;
  "fotmob-stats-categories": FotmobStatsCategoriesResponse;
  "fotmob-table": FotmobTableResponse;
  "fotmob-team": FotmobTeamResponse;
  "fotmob-team-fixtures": FotmobTeamFixturesResponse;
  "fotmob-team-news": FotmobTeamNewsResponse;
  "fotmob-transfers": FotmobTransfersResponse;
  "fotmob-trending-news": FotmobTrendingNewsResponse;
  "fotmob-trending-searches": FotmobTrendingSearchesResponse;
  "fotmob-tv-guide": FotmobTvGuideResponse;
  "fotmob-tv-guide-channels": FotmobTvGuideChannelsResponse;
  "fotmob-tv-guide-countries": FotmobTvGuideCountriesResponse;
}

export interface OperationRequiredParamsMap {
  "fotmob-audio-matches": false;
  "fotmob-fifa-ranking-periods": true;
  "fotmob-fifa-rankings": true;
  "fotmob-latest-news": false;
  "fotmob-league": true;
  "fotmob-leagues": false;
  "fotmob-lineup-builder-players": true;
  "fotmob-lineup-builder-team": true;
  "fotmob-match": true;
  "fotmob-match-media": true;
  "fotmob-matches": true;
  "fotmob-news": true;
  "fotmob-news-article": true;
  "fotmob-player": true;
  "fotmob-player-match-stats": true;
  "fotmob-player-matches": true;
  "fotmob-player-stats": true;
  "fotmob-search": true;
  "fotmob-seasons": true;
  "fotmob-stats": true;
  "fotmob-stats-categories": true;
  "fotmob-table": true;
  "fotmob-team": true;
  "fotmob-team-fixtures": true;
  "fotmob-team-news": true;
  "fotmob-transfers": false;
  "fotmob-trending-news": false;
  "fotmob-trending-searches": false;
  "fotmob-tv-guide": true;
  "fotmob-tv-guide-channels": true;
  "fotmob-tv-guide-countries": false;
}

export type OperationId = keyof OperationParamsMap;

export type OperationRequestArgs<I extends OperationId> =
  OperationRequiredParamsMap[I] extends true
    ? [params: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions]
    : [params?: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions];

export type OperationIdLiteral =
  | "fotmob-audio-matches"
  | "fotmob-fifa-ranking-periods"
  | "fotmob-fifa-rankings"
  | "fotmob-latest-news"
  | "fotmob-league"
  | "fotmob-leagues"
  | "fotmob-lineup-builder-players"
  | "fotmob-lineup-builder-team"
  | "fotmob-match"
  | "fotmob-match-media"
  | "fotmob-matches"
  | "fotmob-news"
  | "fotmob-news-article"
  | "fotmob-player"
  | "fotmob-player-match-stats"
  | "fotmob-player-matches"
  | "fotmob-player-stats"
  | "fotmob-search"
  | "fotmob-seasons"
  | "fotmob-stats"
  | "fotmob-stats-categories"
  | "fotmob-table"
  | "fotmob-team"
  | "fotmob-team-fixtures"
  | "fotmob-team-news"
  | "fotmob-transfers"
  | "fotmob-trending-news"
  | "fotmob-trending-searches"
  | "fotmob-tv-guide"
  | "fotmob-tv-guide-channels"
  | "fotmob-tv-guide-countries";

export declare const OperationIds: Readonly<{
  FotmobAudioMatches: "fotmob-audio-matches";
  FotmobFifaRankingPeriods: "fotmob-fifa-ranking-periods";
  FotmobFifaRankings: "fotmob-fifa-rankings";
  FotmobLatestNews: "fotmob-latest-news";
  FotmobLeague: "fotmob-league";
  FotmobLeagues: "fotmob-leagues";
  FotmobLineupBuilderPlayers: "fotmob-lineup-builder-players";
  FotmobLineupBuilderTeam: "fotmob-lineup-builder-team";
  FotmobMatch: "fotmob-match";
  FotmobMatchMedia: "fotmob-match-media";
  FotmobMatches: "fotmob-matches";
  FotmobNews: "fotmob-news";
  FotmobNewsArticle: "fotmob-news-article";
  FotmobPlayer: "fotmob-player";
  FotmobPlayerMatchStats: "fotmob-player-match-stats";
  FotmobPlayerMatches: "fotmob-player-matches";
  FotmobPlayerStats: "fotmob-player-stats";
  FotmobSearch: "fotmob-search";
  FotmobSeasons: "fotmob-seasons";
  FotmobStats: "fotmob-stats";
  FotmobStatsCategories: "fotmob-stats-categories";
  FotmobTable: "fotmob-table";
  FotmobTeam: "fotmob-team";
  FotmobTeamFixtures: "fotmob-team-fixtures";
  FotmobTeamNews: "fotmob-team-news";
  FotmobTransfers: "fotmob-transfers";
  FotmobTrendingNews: "fotmob-trending-news";
  FotmobTrendingSearches: "fotmob-trending-searches";
  FotmobTvGuide: "fotmob-tv-guide";
  FotmobTvGuideChannels: "fotmob-tv-guide-channels";
  FotmobTvGuideCountries: "fotmob-tv-guide-countries";
}>;
