// Code generated by the Crawlora platform SDK generator. DO NOT EDIT.

package fotmob

import (
	"context"
	"sort"

	crawlora "github.com/Crawlora-org/crawlora-go-sdk"
)

type parameterDefinition struct {
	Name             string
	In               string
	Type             string
	CollectionFormat string
	Required         bool
	Enum             []string
}

type operationDefinition struct {
	Method      string
	Path        string
	PathParams  []string
	QueryParams []parameterDefinition
	Produces    []string
	Security    []string
}

var operations = map[string]operationDefinition{
	"fotmob-audio-matches":          operationDefinition{Method: "GET", Path: "/fotmob/audio-matches", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-fifa-ranking-periods":   operationDefinition{Method: "GET", Path: "/fotmob/fifa-ranking-periods", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "gender", In: "query", Type: "string", Required: true, Enum: []string{"men", "women"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-fifa-rankings":          operationDefinition{Method: "GET", Path: "/fotmob/fifa-rankings", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "gender", In: "query", Type: "string", Required: true, Enum: []string{"men", "women"}}, parameterDefinition{Name: "period_id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-latest-news":            operationDefinition{Method: "GET", Path: "/fotmob/latest-news", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "start_index", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-league":                 operationDefinition{Method: "GET", Path: "/fotmob/league", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "league_id", In: "query", Type: "integer", Required: true}, parameterDefinition{Name: "season", In: "query", Type: "string"}, parameterDefinition{Name: "shotmap", In: "query", Type: "boolean"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-leagues":                operationDefinition{Method: "GET", Path: "/fotmob/leagues", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-lineup-builder-players": operationDefinition{Method: "GET", Path: "/fotmob/lineup-builder-players", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "player_ids", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-lineup-builder-team":    operationDefinition{Method: "GET", Path: "/fotmob/lineup-builder-team", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "team_id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-match":                  operationDefinition{Method: "GET", Path: "/fotmob/match", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-match-media":            operationDefinition{Method: "GET", Path: "/fotmob/match-media", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-matches":                operationDefinition{Method: "GET", Path: "/fotmob/matches", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "date", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "timezone", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-news":                   operationDefinition{Method: "GET", Path: "/fotmob/news", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "league_id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "start_index", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-news-article":           operationDefinition{Method: "GET", Path: "/fotmob/news-article", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-player":                 operationDefinition{Method: "GET", Path: "/fotmob/player", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "include_market_values", In: "query", Type: "boolean"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-player-match-stats":     operationDefinition{Method: "GET", Path: "/fotmob/player-match-stats", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "player_id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "match_id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-player-matches":         operationDefinition{Method: "GET", Path: "/fotmob/player-matches", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "player_id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "league_id", In: "query", Type: "string"}, parameterDefinition{Name: "team_id", In: "query", Type: "string"}, parameterDefinition{Name: "before", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-player-stats":           operationDefinition{Method: "GET", Path: "/fotmob/player-stats", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "player_id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "season_id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-search":                 operationDefinition{Method: "GET", Path: "/fotmob/search", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "term", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-seasons":                operationDefinition{Method: "GET", Path: "/fotmob/seasons", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "league_id", In: "query", Type: "integer", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-stats":                  operationDefinition{Method: "GET", Path: "/fotmob/stats", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "league_id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "season_id", In: "query", Type: "string"}, parameterDefinition{Name: "type", In: "query", Type: "string", Required: true, Enum: []string{"players", "teams"}}, parameterDefinition{Name: "stat", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "team_id", In: "query", Type: "string"}, parameterDefinition{Name: "position", In: "query", Type: "string", Enum: []string{"all", "striker", "winger", "attackingMidfielder", "midfielder", "fullback", "centerBack"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-stats-categories":       operationDefinition{Method: "GET", Path: "/fotmob/stats-categories", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "league_id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "season_id", In: "query", Type: "string"}, parameterDefinition{Name: "type", In: "query", Type: "string", Required: true, Enum: []string{"players", "teams"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-table":                  operationDefinition{Method: "GET", Path: "/fotmob/table", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "league_id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-team":                   operationDefinition{Method: "GET", Path: "/fotmob/team", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-team-fixtures":          operationDefinition{Method: "GET", Path: "/fotmob/team-fixtures", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "team_id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "cursor", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-team-news":              operationDefinition{Method: "GET", Path: "/fotmob/team-news", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "team_id", In: "query", Type: "integer", Required: true}, parameterDefinition{Name: "start_index", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-transfers":              operationDefinition{Method: "GET", Path: "/fotmob/transfers", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "mode", In: "query", Type: "string", Enum: []string{"all", "rumours", "popular"}}, parameterDefinition{Name: "page", In: "query", Type: "integer"}, parameterDefinition{Name: "last", In: "query", Type: "string", Enum: []string{"6months", "1year", "2years", "3years"}}, parameterDefinition{Name: "direction", In: "query", Type: "string", Enum: []string{"all", "in", "out"}}, parameterDefinition{Name: "min_fee", In: "query", Type: "integer"}, parameterDefinition{Name: "max_fee", In: "query", Type: "integer"}, parameterDefinition{Name: "league_ids", In: "query", Type: "string"}, parameterDefinition{Name: "team_ids", In: "query", Type: "string"}, parameterDefinition{Name: "order_by", In: "query", Type: "string", Enum: []string{"lastModified", "fee", "date", "name", "fromClubName", "toClubName"}}, parameterDefinition{Name: "exclude_extensions", In: "query", Type: "boolean"}, parameterDefinition{Name: "likely_only", In: "query", Type: "boolean"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-trending-news":          operationDefinition{Method: "GET", Path: "/fotmob/trending-news", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-trending-searches":      operationDefinition{Method: "GET", Path: "/fotmob/trending-searches", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-tv-guide":               operationDefinition{Method: "GET", Path: "/fotmob/tv-guide", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "country", In: "query", Type: "string", Required: true, Enum: []string{"us", "se", "gb", "de", "no", "es", "mx", "ar", "bo", "cl", "co", "cr", "ec", "gt", "hn", "ni", "pa", "py", "pe", "uy", "ve", "da", "ca", "au", "at", "be", "bg", "hr", "cy", "cz", "ee", "fi", "fr", "gr", "hu", "is", "ie", "il", "it", "nl", "pl", "pt", "ro", "ru", "ch", "tr", "za", "br", "in", "me", "id", "th", "mm", "al", "az", "bl", "ba", "ks", "la", "li", "mk", "rs", "sk", "ua", "essv", "nz", "bd", "cn", "gh", "hk", "jp", "kr", "ma", "mt", "my", "ng", "ph", "pk", "sg", "si", "tz"}}, parameterDefinition{Name: "timezone", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-tv-guide-channels":      operationDefinition{Method: "GET", Path: "/fotmob/tv-guide-channels", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "country", In: "query", Type: "string", Required: true, Enum: []string{"us", "se", "gb", "de", "no", "es", "mx", "ar", "bo", "cl", "co", "cr", "ec", "gt", "hn", "ni", "pa", "py", "pe", "uy", "ve", "da", "ca", "au", "at", "be", "bg", "hr", "cy", "cz", "ee", "fi", "fr", "gr", "hu", "is", "ie", "il", "it", "nl", "pl", "pt", "ro", "ru", "ch", "tr", "za", "br", "in", "me", "id", "th", "mm", "al", "az", "bl", "ba", "ks", "la", "li", "mk", "rs", "sk", "ua", "essv", "nz", "bd", "cn", "gh", "hk", "jp", "kr", "ma", "mt", "my", "ng", "ph", "pk", "sg", "si", "tz"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"fotmob-tv-guide-countries":     operationDefinition{Method: "GET", Path: "/fotmob/tv-guide-countries", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
}

// OperationCount reports how many selected-platform operations this module exposes.
const OperationCount = 31

// OperationIDs returns the selected operation IDs in stable sorted order.
func OperationIDs() []string {
	ids := make([]string, 0, len(operations))
	for id := range operations {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

// AudioMatches calls the fotmob-audio-matches operation.
func (c *Client) AudioMatches(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-audio-matches", params)
}

// FifaRankingPeriods calls the fotmob-fifa-ranking-periods operation.
func (c *Client) FifaRankingPeriods(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-fifa-ranking-periods", params)
}

// FifaRankings calls the fotmob-fifa-rankings operation.
func (c *Client) FifaRankings(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-fifa-rankings", params)
}

// LatestNews calls the fotmob-latest-news operation.
func (c *Client) LatestNews(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-latest-news", params)
}

// League calls the fotmob-league operation.
func (c *Client) League(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-league", params)
}

// Leagues calls the fotmob-leagues operation.
func (c *Client) Leagues(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-leagues", params)
}

// LineupBuilderPlayers calls the fotmob-lineup-builder-players operation.
func (c *Client) LineupBuilderPlayers(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-lineup-builder-players", params)
}

// LineupBuilderTeam calls the fotmob-lineup-builder-team operation.
func (c *Client) LineupBuilderTeam(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-lineup-builder-team", params)
}

// Match calls the fotmob-match operation.
func (c *Client) Match(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-match", params)
}

// MatchMedia calls the fotmob-match-media operation.
func (c *Client) MatchMedia(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-match-media", params)
}

// Matches calls the fotmob-matches operation.
func (c *Client) Matches(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-matches", params)
}

// News calls the fotmob-news operation.
func (c *Client) News(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-news", params)
}

// NewsArticle calls the fotmob-news-article operation.
func (c *Client) NewsArticle(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-news-article", params)
}

// Player calls the fotmob-player operation.
func (c *Client) Player(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-player", params)
}

// PlayerMatchStats calls the fotmob-player-match-stats operation.
func (c *Client) PlayerMatchStats(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-player-match-stats", params)
}

// PlayerMatches calls the fotmob-player-matches operation.
func (c *Client) PlayerMatches(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-player-matches", params)
}

// PlayerStats calls the fotmob-player-stats operation.
func (c *Client) PlayerStats(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-player-stats", params)
}

// Search calls the fotmob-search operation.
func (c *Client) Search(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-search", params)
}

// Seasons calls the fotmob-seasons operation.
func (c *Client) Seasons(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-seasons", params)
}

// Stats calls the fotmob-stats operation.
func (c *Client) Stats(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-stats", params)
}

// StatsCategories calls the fotmob-stats-categories operation.
func (c *Client) StatsCategories(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-stats-categories", params)
}

// Table calls the fotmob-table operation.
func (c *Client) Table(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-table", params)
}

// Team calls the fotmob-team operation.
func (c *Client) Team(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-team", params)
}

// TeamFixtures calls the fotmob-team-fixtures operation.
func (c *Client) TeamFixtures(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-team-fixtures", params)
}

// TeamNews calls the fotmob-team-news operation.
func (c *Client) TeamNews(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-team-news", params)
}

// Transfers calls the fotmob-transfers operation.
func (c *Client) Transfers(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-transfers", params)
}

// TrendingNews calls the fotmob-trending-news operation.
func (c *Client) TrendingNews(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-trending-news", params)
}

// TrendingSearches calls the fotmob-trending-searches operation.
func (c *Client) TrendingSearches(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-trending-searches", params)
}

// TvGuide calls the fotmob-tv-guide operation.
func (c *Client) TvGuide(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-tv-guide", params)
}

// TvGuideChannels calls the fotmob-tv-guide-channels operation.
func (c *Client) TvGuideChannels(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-tv-guide-channels", params)
}

// TvGuideCountries calls the fotmob-tv-guide-countries operation.
func (c *Client) TvGuideCountries(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "fotmob-tv-guide-countries", params)
}
